### ISSUE TITLE
Signup Error

### ISSUE THREAD

**Issue by aalinia** [appwrite/demo-todo-with-react#32]
### 👟 Reproduction steps

When I try to signup to the demo app.

### 👍 Expected behavior

It should either signup or show the error message.

### 👎 Actual Behavior

It actually does nothing with no error message.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

version: 0.12

Request:
`POST https://demo.appwrite.io/v1/account
`
Error:
```
code: 400
message: "Param \"userId\" is not optional."
version: "0.12.0"
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by DmacMcgreg** [comment]
This is still happening, cannot signup
