### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by timo-tech19** [appwrite/demo-todo-with-react#37]
### 👟 Reproduction steps

When I fill in the login or sign up form and press the submit button, nothing happens 

### 👍 Expected behavior

I should be able to sign up and maybe route to another page

### 👎 Actual Behavior

Nothing happens. The buttons don't work

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Something else

### 🧱 Your Environment

Mobile phone. Chrome browser . I am not sure of the AppWrite version

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by achyutghosh** [comment]
The same issue is happing while testing it on my laptop. However, in the console, I have found the issue given below

`{"message":"Account already exists","code":409,"version":"0.14.2"}`

Here the point to be noted is that I try to sign up for the first time, so there are zero chance that the account may already exists
