### ISSUE TITLE
🚀 Feature: Update the logo to AppWrite from React default logo and change name from React App to "To Do App"

### ISSUE THREAD

**Issue by knight-95** [appwrite/demo-todo-with-react#45]
### 🔖 Feature description

Appwrite logo in PNG format instead of React default logo
Change name from React App to " To Do App"

### 🎤 Pitch

It looks professional

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by GauravPoosarla** [comment]
Can I work on this?

**Comment by ranodeepbanerjee** [comment]
Please assign this to me. Thanks

**Comment by RafaelDavisH** [comment]
I would like to give a shot to this issue.

**Comment by knight-95** [comment]
> ### 🔖 Feature description
> Appwrite logo in PNG format instead of React default logo Change name from React App to " To Do App"
> 
> ### 🎤 Pitch
> It looks professional
> 
> ### 👀 Have you spent some time to check if this issue has been raised before?
> * [x]  I checked and didn't find similar issue
> 
> ### 🏢 Have you read the Code of Conduct?
> * [x]  I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

I would like to work on this, I have already identified the areas to change and work upon. Thanks!

**Comment by ezefranca** [comment]
https://github.com/appwrite/demo-todo-with-react/pull/46

**Comment by rajivransom** [comment]
Can you please assign this task to me?

**Comment by DharuvVerma21** [comment]
Hi! Can you please assign this task to me?

**Comment by TayyabHussain03** [comment]
Please assign it to me. I would like to give a shot to this issue & i will work on thi project with my exprtize. Thanks

**Comment by Srishtihere** [comment]
hello can I work on this

**Comment by Shamik1836** [comment]
I can work on this issue, right away, can you please assign this to me

**Comment by Mr-vabs** [comment]
Hello, can you assign this task to me??

**Comment by stnguyen90** [comment]
@knight-95, thanks for raising this issue! 🙏 Unfortunately, we'd rather people focus on the issues we created as those issues create more of an impact. I'm going to close this issue for now since it's attracting a lot of extra attention during Hacktoberfest.

If you'd like to contribute, you can try exploring hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/). If you have any problems or need help, please join our [Discord community](https://appwrite.io/discord) and use the `#hacktoberfest` channel.
