### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by muzammilsyed** [appwrite/demo-todo-with-react#69]
### 👟 Reproduction steps

same database collection are showing for any user login or sign up

### 👍 Expected behavior

need a separate DB collection for individual users. what went wrong? in my cloud appwrite config need to be work on?

### 👎 Actual Behavior

same database collection are showing for any user login or sign up

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by adityaoberai** [comment]
Hi @muzammilsyed 
Each document (todo) in the collection has its permissions set in a way that only the user who creates a document can read, update, or delete it. Therefore, even in the same collection, a user would only be able to access their own todos only.

You should enable **Document Level Security** in your Collection settings once to fix this.

**Comment by muzammilsyed** [comment]
Thanks @adityaoberai. I enabled Document Level Security and now working fine.
