### ISSUE TITLE
🚀 Feature: Let's introduce priority levels !

### ISSUE THREAD

**Issue by Candy505** [appwrite/demo-todo-with-react#72]
### 🔖 Feature description

To allow users to decide priority levels (high, medium, low) for their tasks, helping them focus on what's most important.
We can associate each level with a color code  for ex -

High Priority: Red
Medium Priority: Orange
Low Priority: Green

### 🎤 Pitch

Adding color-coded priority levels to tasks in a to-do app makes it easier for people to see which tasks are most important. This helps to get things done faster and stay organized as humans are visual beings.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Candy505** [comment]
I would like to work on this. Can you assign it to me?

**Comment by prathamesh3707** [comment]
I can do it!

**Comment by stnguyen90** [comment]
@Candy505 Unfortunately, we don't want to add this at the moment. If you wish to contribute as part of Hacktoberfest, please look for issues labeled "hacktoberfest".
